### ISSUE TITLE
ExtendedRelationIsDescriptor.php does not seem to work

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_relation_is_descriptor#3]
First of all, thanks for the effort in creating this module!

I tested it with webtrees 2.0.19.

1.  I added three relations (`twin`, `triplet`, `minister`) in **RelationIsDescriptorAddon.php**, and their translations in **ExtendedRelationIsDescriptor.php**.
2. Then I removed these relations from **app/Elements/RelationIsDescriptor.php**  (where I had previously added them) and I disabled my translation module.

At that point, these relationships are **not** translated.

The translations do work when I add these relations back to **app/Elements/RelationIsDescriptor.php**. Therefore, it seems that **ExtendedRelationIsDescriptor.php** is not working.

Also, the relation type `minister` is not available in the associates drop-down menu because it's missing in **app/GedcomCode/GedcomCodeRela.php**:
![afbeelding](https://user-images.githubusercontent.com/46184729/147055730-de87be28-356d-4661-a6c9-f31adbd09074.png)

**Comment by ric2016** [comment]
I linked to the 2.1 version of the ElementFactory in the forum thread, which only has one entry for RelationIsDescriptor. The current 2.0 version has three others (in 'Gedcom-L extensions'), which likely also have to be overwritten, [see this file](https://github.com/fisharebest/webtrees/blob/fbee77dd67c6e7e0a6a97ce2fee7cc85856f8fa5/app/Factories/ElementFactory.php#L630).

Regarding the use of GedcomCodeRela.php: That's not good. Maybe this is handled better in 2.1, in 2.0 there is no clean way to override this file. The easiest solution is probably to swap it out altogether. Vesta does this for a few files as a last resort, [see e.g. the code starting here](https://github.com/vesta-webtrees-2-custom-modules/vesta_common/blob/38e1feee0c08c4e37d5bb311810ed3ff2dbed975/autoload.php#L23).

**Comment by hartenthaler** [comment]
My development environment is already based on webtrees 2.1. Then I checked it very short with 2.0.19 and did not see an error, but the test was too short. Now I added support for FAM:*:_ASSO:RELA, INDI:*:ASSO:RELA, and FAM:*:_ASSO:RELA.

**Comment by hartenthaler** [comment]
As far as I can see, the module is working under webtrees 2.1. 

I do not plan to solve the problem with GedcomCodeRela.php in webtrees 2.0. As far as I have tested it, the module should show (and translate) custom relation descriptors in webtrees 2.0.19 with the next release. But you will not see the custom values in the selection menu, i.e. you have to edit raw GEDCOM if you like to add new custom relations to a person, a family, or an event.

**Comment by hartenthaler** [comment]
In the latest version of webtrees 2.1 the function "register" was removed. I used this function to register new relation descriptors. Now I'm lost. The core of my module is in RelationIsDescriptorAddon.php in line 197ff in function boot(). I do not have any idea how to register new relation descriptors.

**Comment by ric2016** [comment]
> In the latest version of webtrees 2.1 the function "register" was removed

It has been renamed to 'registerTags'.

**Comment by hartenthaler** [comment]
@ric2016 thanks a lot! so easy! Now it is working.

@TheDutchJewel it would be nice if you can test this release now together with webtrees 2.1

**Comment by TheDutchJewel** [comment]
@hartenthaler your module works fine!

I tested version 2.1.1.0 with webtrees 2.1.1.

1. First I checked what happened when I removed three relations (`minister`, `twin` and `triplet`) from **app/Elements/RelationIsDescriptor.php** (where I had previously added them): now the relations **were not** shown in the associates drop-down menu, as expected.

2. Then I added the relations in **h_relation_is_descriptor\ExtendedRelationIsDescriptor.php**, and tried again: now the relations **were** shown in the associates drop-down menu, which is OK.

The translation also works fine by adding these terms to the translation module (which is an modified version of the [example module](https://github.com/webtrees/example-module)), or by adding them at the end of the file **hh_relation_is_descriptor\RelationIsDescriptorAddon.php**.

**Comment by hartenthaler** [comment]
@TheDutchJewel Thanks for testing!
